// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SunDaySchoolsDAL.DBcontext;

#nullable disable

namespace SunDaySchools.DAL.Migrations
{
    [DbContext(typeof(ProgramContext))]
    [Migration("20260525120000_AddWhatsAppOtpVerification")]
    partial class AddWhatsAppOtpVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is defined in ProgramContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
