// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunDaySchoolsDAL.DBcontext;

#nullable disable

namespace SunDaySchools.DAL.Migrations
{
    [DbContext(typeof(ProgramContext))]
    [Migration("20260409143023_edit-the-class-servant-relation")]
    partial class edittheclassservantrelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Church", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PastorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastorId");

                    b.ToTable("Churches");
                });

            modelBuilder.Entity("ClassroomServant", b =>
                {
                    b.Property<int>("ServantId")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.HasKey("ServantId", "ClassroomId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("MeetingId");

                    b.ToTable("ClassroomServant");
                });

            modelBuilder.Entity("MemberContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberContacts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<bool>("HasTools")
                        .HasColumnType("bit");

                    b.Property<bool>("MadeHomeWork")
                        .HasColumnType("bit");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MemberId");

                    b.HasIndex("AttendanceSessionId", "MemberId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.AttendanceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TakenByServantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("TakenByServantId");

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("MeetingId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ExamId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MemberId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<int?>("LeaderServantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Weekly_appointment")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("LeaderServantId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("SunDaySchools.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeOfMembers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<int?>("LeaderServantId")
                        .HasColumnType("int");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfDisplineMembers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("LeaderServantId");

                    b.HasIndex("MeetingId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("SunDaySchools.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrothersNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HaveBrothers")
                        .HasColumnType("bit");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDiscipline")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LastAttendanceDate")
                        .HasColumnType("date");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("SpiritualDateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("TotalNumberOfDaysAttended")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("MeetingId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SunDaySchools.Models.Servant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingId");

                    b.ToTable("Servants");
                });

            modelBuilder.Entity("SunDaySchools.Models.SpiritualCurriculum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfLastUse")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Exist")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfAvailableStudentBooks")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfAvailableTeacherBooks")
                        .HasColumnType("int");

                    b.Property<int?>("NummberOfLessons")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TokeBefore")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingId");

                    b.ToTable("SpiritualCurriculums");
                });

            modelBuilder.Entity("SunDaySchools.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfLastUse")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("SunDaySchoolsDAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SunDaySchoolsDAL.Models.PhoneCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberContactId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberContactId");

                    b.HasIndex("ServantId");

                    b.ToTable("PhoneCalls");
                });

            modelBuilder.Entity("Church", b =>
                {
                    b.HasOne("SunDaySchools.Models.Servant", "Pastor")
                        .WithMany()
                        .HasForeignKey("PastorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pastor");
                });

            modelBuilder.Entity("ClassroomServant", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.Models.Classroom", "Classroom")
                        .WithMany("ClassroomServants")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.HasOne("SunDaySchools.Models.Servant", "Servant")
                        .WithMany("ClassroomServants")
                        .HasForeignKey("ServantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuch");

                    b.Navigation("Classroom");

                    b.Navigation("Meeting");

                    b.Navigation("Servant");
                });

            modelBuilder.Entity("MemberContact", b =>
                {
                    b.HasOne("SunDaySchools.Models.Member", "Member")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SunDaySchoolsDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SunDaySchoolsDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunDaySchoolsDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SunDaySchoolsDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.AttendanceRecord", b =>
                {
                    b.HasOne("SunDaySchools.DAL.Models.AttendanceSession", "AttendanceSession")
                        .WithMany("Records")
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.HasOne("SunDaySchools.Models.Member", "Member")
                        .WithMany("AttendanceHistory")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceSession");

                    b.Navigation("Chuch");

                    b.Navigation("Meeting");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.AttendanceSession", b =>
                {
                    b.HasOne("SunDaySchools.Models.Classroom", "Classroom")
                        .WithMany("AttendanceHistory")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunDaySchools.Models.Servant", "TakenByServant")
                        .WithMany()
                        .HasForeignKey("TakenByServantId");

                    b.Navigation("Classroom");

                    b.Navigation("TakenByServant");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.Exam", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId");

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Chuch");

                    b.Navigation("Classroom");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.ExamResult", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.DAL.Models.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunDaySchools.Models.Member", "Member")
                        .WithMany("ExamsResults")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chuch");

                    b.Navigation("Exam");

                    b.Navigation("Meeting");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.Meeting", b =>
                {
                    b.HasOne("Church", "Church")
                        .WithMany("Meetings")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunDaySchools.Models.Servant", "LeaderServant")
                        .WithMany()
                        .HasForeignKey("LeaderServantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Church");

                    b.Navigation("LeaderServant");
                });

            modelBuilder.Entity("SunDaySchools.Models.Classroom", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.Models.Servant", "LeaderServant")
                        .WithMany()
                        .HasForeignKey("LeaderServantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Chuch");

                    b.Navigation("LeaderServant");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchools.Models.Member", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.Models.Classroom", "Classroom")
                        .WithMany("Members")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany("Members")
                        .HasForeignKey("MeetingId");

                    b.Navigation("Chuch");

                    b.Navigation("Classroom");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchools.Models.Servant", b =>
                {
                    b.HasOne("SunDaySchoolsDAL.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("ServantProfile")
                        .HasForeignKey("SunDaySchools.Models.Servant", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Church", "Chuch")
                        .WithMany("Servants")
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany("Servants")
                        .HasForeignKey("MeetingId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Chuch");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchools.Models.SpiritualCurriculum", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Chuch");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchools.Models.Tool", b =>
                {
                    b.HasOne("Church", "Chuch")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Chuch");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchoolsDAL.Models.ApplicationUser", b =>
                {
                    b.HasOne("Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId");

                    b.HasOne("SunDaySchools.DAL.Models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Church");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("SunDaySchoolsDAL.Models.PhoneCall", b =>
                {
                    b.HasOne("MemberContact", "MemberContact")
                        .WithMany("CallsHistory")
                        .HasForeignKey("MemberContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunDaySchools.Models.Servant", "Servant")
                        .WithMany()
                        .HasForeignKey("ServantId");

                    b.Navigation("MemberContact");

                    b.Navigation("Servant");
                });

            modelBuilder.Entity("Church", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Members");

                    b.Navigation("Servants");
                });

            modelBuilder.Entity("MemberContact", b =>
                {
                    b.Navigation("CallsHistory");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.AttendanceSession", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.Exam", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("SunDaySchools.DAL.Models.Meeting", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Servants");
                });

            modelBuilder.Entity("SunDaySchools.Models.Classroom", b =>
                {
                    b.Navigation("AttendanceHistory");

                    b.Navigation("ClassroomServants");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("SunDaySchools.Models.Member", b =>
                {
                    b.Navigation("AttendanceHistory");

                    b.Navigation("ExamsResults");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("SunDaySchools.Models.Servant", b =>
                {
                    b.Navigation("ClassroomServants");
                });

            modelBuilder.Entity("SunDaySchoolsDAL.Models.ApplicationUser", b =>
                {
                    b.Navigation("ServantProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
